#!/usr/bin/perl -w

# Generates the input files for the ANMPathway method.

$NUM_PARTICLES = 214; 
$CUT_OFF_1 = 15.0;
$CUT_OFF_2 = 15.0;
$FORCE_CONSTANT_1 = 0.1;
$FORCE_CONSTANT_2 = 0.1;
$ENERGY_OFFSET_1 = 5.0;
$ENERGY_OFFSET_2 = 0.0;
$CUSP_TOLERANCE = 1.0e-5;
$NUM_IMAGES_INTERPOLATE = 100;
$STEP_SIZE_MINIMIZE_ON_CUSP_1 = 0.8;
$STEP_SIZE_MINIMIZE_ON_CUSP_2 = 0.8;
$NUM_ITER_CHECK_STEP_SIZES = 20;
$STEP_SIZE_REDUCTION_FACTOR_MINIMIZE_ON_CUSP_1 = 0.5;
$STEP_SIZE_REDUCTION_FACTOR_MINIMIZE_ON_CUSP_2 = 0.5;
$ENERGY_TOL_CONVERGENCE_MINIMIZE_ON_CUSP = 0.001;
$NUM_ITERATIONS_MINIMIZE_ON_CUSP = 10000;
$STEP_SIZE_SLIDE_DOWN_1 = 0.04;
$STEP_SIZE_SLIDE_DOWN_2 = 0.04;
$STEP_SIZE_REDUCTION_FACTOR_SLIDE_DOWN_1 = 0.9;
$STEP_SIZE_REDUCTION_FACTOR_SLIDE_DOWN_2 = 0.9;
$RMSD_PATHWAY = 0.1;
$RMSD_DIFF_TOL = 0.01;
$ENERGY_FROM_REFERENCE_TOL = 0.01;
$MAX_NUM_ITER_SLIDE_DOWN = 1000000;

## Step 1
open(OUT, ">INPUT_FIND_STRUCTURE_ON_CUSP");
print OUT "NUM_PARTICLES $NUM_PARTICLES\n"; 
print OUT "CUT_OFFS $CUT_OFF_1 $CUT_OFF_2\n";
print OUT "FORCE_CONSTANTS $FORCE_CONSTANT_1 $FORCE_CONSTANT_2\n";
print OUT "ENERGY_OFFSETS $ENERGY_OFFSET_1 $ENERGY_OFFSET_2\n";
print OUT "CUSP_TOLERANCE $CUSP_TOLERANCE\n";
print OUT "NUM_IMAGES_INTERPOLATE $NUM_IMAGES_INTERPOLATE\n";
close(OUT); 

## Step 2
$CUSP_TOLERANCE = 1.0e-4;
open(OUT, ">INPUT_MINIMIZE_ON_CUSP");
print OUT "NUM_PARTICLES $NUM_PARTICLES\n";
print OUT "CUT_OFFS $CUT_OFF_1 $CUT_OFF_2\n";
print OUT "FORCE_CONSTANTS $FORCE_CONSTANT_1 $FORCE_CONSTANT_2\n";
print OUT "ENERGY_OFFSETS $ENERGY_OFFSET_1 $ENERGY_OFFSET_2\n";
print OUT "CUSP_TOLERANCE $CUSP_TOLERANCE\n";
print OUT "NUM_IMAGES_INTERPOLATE $NUM_IMAGES_INTERPOLATE\n";
print OUT "STEP_SIZES $STEP_SIZE_MINIMIZE_ON_CUSP_1 $STEP_SIZE_MINIMIZE_ON_CUSP_2\n";
print OUT "NUM_ITER_CHECK_STEP_SIZES $NUM_ITER_CHECK_STEP_SIZES\n";
print OUT "STEP_SIZE_REDUCTION_FACTORS $STEP_SIZE_REDUCTION_FACTOR_MINIMIZE_ON_CUSP_1 $STEP_SIZE_REDUCTION_FACTOR_MINIMIZE_ON_CUSP_2\n";
print OUT "ENERGY_TOL_CONVERGENCE $ENERGY_TOL_CONVERGENCE_MINIMIZE_ON_CUSP\n";
print OUT "NUM_ITERATIONS $NUM_ITERATIONS_MINIMIZE_ON_CUSP\n";
close(OUT);


## Step 3
### Surface 1
open(OUT, ">INPUT_SLIDE_ONE_SURFACE_1");
print OUT "NUM_PARTICLES $NUM_PARTICLES\n";
print OUT "SURFACE_INDEX 1\n";
print OUT "CUT_OFF $CUT_OFF_1\n";
print OUT "FORCE_CONSTANT $FORCE_CONSTANT_1\n";
print OUT "ENERGY_OFFSET $ENERGY_OFFSET_1\n";
print OUT "STEP_SIZE $STEP_SIZE_SLIDE_DOWN_1\n";
print OUT "STEP_SIZE_REDUCTION_FACTOR $STEP_SIZE_REDUCTION_FACTOR_SLIDE_DOWN_1\n";
print OUT "RMSD_PATHWAY $RMSD_PATHWAY\n";
print OUT "RMSD_DIFF_TOL $RMSD_DIFF_TOL\n";
print OUT "ENERGY_FROM_REFERENCE_TOL $ENERGY_FROM_REFERENCE_TOL\n";
print OUT "MAX_NUM_ITER $MAX_NUM_ITER_SLIDE_DOWN\n";
close(OUT);
### Surface 2
open(OUT, ">INPUT_SLIDE_ONE_SURFACE_2");
print OUT "NUM_PARTICLES $NUM_PARTICLES\n";
print OUT "SURFACE_INDEX 2\n";
print OUT "CUT_OFF $CUT_OFF_2\n";
print OUT "FORCE_CONSTANT $FORCE_CONSTANT_2\n";
print OUT "ENERGY_OFFSET $ENERGY_OFFSET_2\n";
print OUT "STEP_SIZE $STEP_SIZE_SLIDE_DOWN_2\n";
print OUT "STEP_SIZE_REDUCTION_FACTOR $STEP_SIZE_REDUCTION_FACTOR_SLIDE_DOWN_2\n";
print OUT "RMSD_PATHWAY $RMSD_PATHWAY\n";
print OUT "RMSD_DIFF_TOL $RMSD_DIFF_TOL\n";
print OUT "ENERGY_FROM_REFERENCE_TOL $ENERGY_FROM_REFERENCE_TOL\n";
print OUT "MAX_NUM_ITER $MAX_NUM_ITER_SLIDE_DOWN\n";
close(OUT);


## Step 3
open(OUT, ">INPUT_COLLECT_ENERGY");
print OUT "NUM_PARTICLES $NUM_PARTICLES\n";
print OUT "CUT_OFFS $CUT_OFF_1 $CUT_OFF_2\n";
print OUT "FORCE_CONSTANTS $FORCE_CONSTANT_1 $FORCE_CONSTANT_2\n";
print OUT "ENERGY_OFFSETS $ENERGY_OFFSET_1 $ENERGY_OFFSET_2\n";
close(OUT);







