clean:
    rm */*.o step-1-find-initial-point/1_locate_struct_on_cusp_v2 step-2-minimize-on-cusp/2_find_min_on_cusp_v4 step-3-slide-down/3_desc_one_surface_v3 step-4-collect-structures/4_collec_ener_v2 step-5-make-pathway/5_makepathway_v2;
